name: Node.js Dist Diff

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm i
      - name: Check linting
        run: npm run lint
      - name: Run builds
        run: npm run build
      - name: Check Files Diff (Should fail when we have any single file change)
        run: npm run test:git
